FROM fnproject/python:3.11-dev AS build-stage
WORKDIR /function
COPY requirements.txt /function/
RUN pip3 install --target /python/ --no-cache-dir --no-deps fdk==0.1.117 \
    && pip3 install --target /python/ --no-cache-dir -r requirements.txt \
    && rm -rf /root/.cache/pip /tmp/* /function/requirements.txt \
    && chmod -R o+r /python
COPY . /function/

FROM fnproject/python:3.11
WORKDIR /function
COPY --from=build-stage /python /python
COPY --from=build-stage /function /function
RUN chmod -R o+r /function
ENV PYTHONPATH=/function:/python
ENTRYPOINT ["/python/bin/fdk", "/function/func.py", "handler"]
